---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🏷️ Latest Semantic Tag"

outputs:
  LATEST-SEMANTIC-TAG:
    description: "Return the latest semantic tag from local repository"
    value: ${{ steps.parse-tags.outputs.latest-semantic }}

runs:
  using: "composite"
  steps:
    - id: parse-tags
      name: "Determines the latest semantic tag"
      shell: bash
      run: |
        latest-semantic=$(git tag -l --sort=committerdate | grep -o 'v.*' | sort -r | head -1)
        echo "latest-semantic=$latest-semantic" >> "$GITHUB_OUTPUT"
        echo "Latest semantic tag = $latest-semantic"
